spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/attendance_system?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  cache:
    type: redis

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  pool:
    max-active: 100
    max-idle: 10
    max-wait: 100000
  timeout: 0

logging:
  level:
     com.example.demo.mapper: debug